# Generated by Django 4.1.6 on 2023-02-14 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_purchase_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='quantity',
            new_name='quantity_purchased',
        ),
    ]
