# Generated by Django 4.1.6 on 2023-02-19 08:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0006_rename_quantity_purchase_quantity_purchased'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'product')},
        ),
    ]
